export const dummyOferta = {
  documentosHabilitantes: [
    {
      tipoDocumento: 'CED',
      identificacion: null,
      excepcionado: false,
      regularizado: false,
      idOficina: 0,
      idUsuario: 0,
      observacion: null,
      usuarioEntrega: null,
      fechaEntrega: null,
      entregado: false,
      numeroReferencia: null,
      idSolicitud: 0,
      descripcionDocumentoHabilitante: 'Papeleta de votacion',
      codigoDocumentoHabilitante: 'DOC01',
      idDocumentoHabilitante: 0,
      numeroSolicitud: null,
      estaEscaneado: false,
      uri: '',
      data: '',
      loaded: false,
    },
    {
      tipoDocumento: 'CED',
      identificacion: null,
      excepcionado: false,
      regularizado: false,
      idOficina: 0,
      idUsuario: 0,
      observacion: null,
      usuarioEntrega: null,
      fechaEntrega: null,
      entregado: false,
      numeroReferencia: null,
      idSolicitud: 0,
      descripcionDocumentoHabilitante: 'Planilla de Luz',
      codigoDocumentoHabilitante: 'DOC02',
      idDocumentoHabilitante: 0,
      numeroSolicitud: null,
      estaEscaneado: false,
      uri: '',
      data: '',
      loaded: false,
    },
    {
      tipoDocumento: 'CED',
      identificacion: null,
      excepcionado: false,
      regularizado: false,
      idOficina: 0,
      idUsuario: 0,
      observacion: null,
      usuarioEntrega: null,
      fechaEntrega: null,
      entregado: false,
      numeroReferencia: null,
      idSolicitud: 0,
      descripcionDocumentoHabilitante: 'Declaracion Juramentada',
      codigoDocumentoHabilitante: 'DOC03',
      idDocumentoHabilitante: 0,
      numeroSolicitud: null,
      estaEscaneado: false,
      uri: '',
      data: '',
      loaded: false,
    },
    {
      tipoDocumento: 'CED',
      identificacion: null,
      excepcionado: false,
      regularizado: false,
      idOficina: 0,
      idUsuario: 0,
      observacion: null,
      usuarioEntrega: null,
      fechaEntrega: null,
      entregado: false,
      numeroReferencia: null,
      idSolicitud: 0,
      descripcionDocumentoHabilitante: 'CEDULA ANVERSO',
      codigoDocumentoHabilitante: 'DOC04',
      idDocumentoHabilitante: 0,
      numeroSolicitud: null,
      estaEscaneado: false,
      uri: '',
      data: '',
      loaded: false,
    },
    {
      tipoDocumento: 'CED',
      identificacion: null,
      excepcionado: false,
      regularizado: false,
      idOficina: 0,
      idUsuario: 0,
      observacion: null,
      usuarioEntrega: null,
      fechaEntrega: null,
      entregado: false,
      numeroReferencia: null,
      idSolicitud: 0,
      descripcionDocumentoHabilitante: 'CEDULA REVERSO',
      codigoDocumentoHabilitante: 'DOC05',
      idDocumentoHabilitante: 0,
      numeroSolicitud: null,
      estaEscaneado: false,
      uri: '',
      data: '',
      loaded: false,
    },
    {
      tipoDocumento: 'CED',
      identificacion: null,
      excepcionado: false,
      regularizado: false,
      idOficina: 0,
      idUsuario: 0,
      observacion: null,
      usuarioEntrega: null,
      fechaEntrega: null,
      entregado: false,
      numeroReferencia: null,
      idSolicitud: 0,
      descripcionDocumentoHabilitante: 'Croquis',
      codigoDocumentoHabilitante: 'DOC06',
      idDocumentoHabilitante: 0,
      numeroSolicitud: null,
      estaEscaneado: false,
      uri: '',
      data: '',
      loaded: false,
    },
  ],
};
