export var GeographicLocation1 = [
    /*{ value: "01", label: "GUATEMALA" },
    { value: "02", label: "EL PROGRESO" },
    { value: "03", label: "SACATEPEQUEZ" },
    { value: "04", label: "CHIMALTENANGO" },
    { value: "05", label: "ESCUINTLA" },
    { value: "06", label: "SANTA ROSA" },
    { value: "07", label: "SOLOLA" },
    { value: "08", label: "TOTONICAPAN" },
    { value: "09", label: "QUETZALTENANGO" },
    { value: "10", label: "SUCHITEPEQUEZ" },
    { value: "11", label: "RETALHULEU" },
    { value: "12", label: "SAN MARCOS" },
    { value: "13", label: "HUEHUETENANGO" },
    { value: "14", label: "QUICHE" },
    { value: "15", label: "BAJA VERAPAZ" },
    { value: "16", label: "ALTA VERAPAZ" },
    { value: "17", label: "PETEN" },
    { value: "18", label: "IZABAL" },
    { value: "19", label: "ZACAPA" },
    { value: "20", label: "CHIQUIMULA" },
    { value: "21", label: "JALAPA" },
    { value: "22", label: "JUTIAPA" },
    { value: "00", label: "NO DEFINIDA" }*/
];

export var GeographicLocation2 = [
   /*{ parent: "01", value: "0101", label: "GUATEMALA" },
    { parent: "01", value: "0102", label: "SANTA CATARINA PINULA" },
    { parent: "01", value: "0103", label: "SAN JOSE PINULA" },
    { parent: "01", value: "0104", label: "SAN JOSE DEL GOLFO" },
    { parent: "01", value: "0105", label: "PALENCIA" },
    { parent: "01", value: "0106", label: "CHINAUTLA" },
    { parent: "01", value: "0107", label: "SAN PEDRO AYAMPUC" },
    { parent: "01", value: "0108", label: "MIXCO" },
    { parent: "01", value: "0109", label: "SAN PEDRO SACATEPEQUEZ" },
    { parent: "01", value: "0110", label: "SAN JUAN SACATEPEQUEZ" },
    { parent: "01", value: "0111", label: "SAN RAYMUNDO" },
    { parent: "01", value: "0112", label: "CHUARRANCHO" },
    { parent: "01", value: "0113", label: "FRAIJANES" },
    { parent: "01", value: "0114", label: "AMATITLAN" },
    { parent: "01", value: "0115", label: "VILLA NUEVA" },
    { parent: "01", value: "0116", label: "VILLA CANALES" },
    { parent: "01", value: "0117", label: "SAN MIGUEL PETAPA" },
    { parent: "02", value: "0201", label: "GUASTATOYA" },
    { parent: "02", value: "0202", label: "MORAZAN" },
    { parent: "02", value: "0203", label: "SAN AGUSTIN ACASAGUASTLAN" },
    { parent: "02", value: "0204", label: "SAN CRISTOBAL ACASAGUASTLAN" },
    { parent: "02", value: "0205", label: "EL JICARO" },
    { parent: "02", value: "0206", label: "SANSARE" },
    { parent: "02", value: "0207", label: "SANARATE" },
    { parent: "02", value: "0208", label: "SAN ANTONIO LA PAZ" },
    { parent: "03", value: "0301", label: "ANTIGUA GUATEMALA" },
    { parent: "03", value: "0302", label: "JOCOTENANGO" },
    { parent: "03", value: "0303", label: "PASTORES" },
    { parent: "03", value: "0304", label: "SUMPANGO" },
    { parent: "03", value: "0305", label: "SANTO DOMINGO XENACOJ" },
    { parent: "03", value: "0306", label: "SANTIAGO SACATEPEQUEZ" },
    { parent: "03", value: "0307", label: "SAN BARTOLOME MILPAS ALTAS" },
    { parent: "03", value: "0308", label: "SAN LUCAS SACATEPEQUEZ" },
    { parent: "03", value: "0309", label: "SANTA LUCIA MILPAS ALTAS" },
    { parent: "03", value: "0310", label: "MAGDALENA MILPAS ALTAS" },
    { parent: "03", value: "0311", label: "SANTA MARIA DE JESUS" },
    { parent: "03", value: "0312", label: "CIUDAD VIEJA" },
    { parent: "03", value: "0313", label: "SAN MIGUEL DUEÑAS" },
    { parent: "03", value: "0314", label: "SAN JUAN ALOTENANGO" },
    { parent: "03", value: "0315", label: "SAN ANTONIO AGUAS CALIENTES" },
    { parent: "03", value: "0316", label: "SANTA CATARINA BARAHONA" },
    { parent: "04", value: "0401", label: "CHIMALTENANGO" },
    { parent: "04", value: "0402", label: "SAN JOSE POAQUIL" },
    { parent: "04", value: "0403", label: "SAN MARTIN JILOTEPEQUE" },
    { parent: "04", value: "0404", label: "SAN JUAN COMALAPA" },
    { parent: "04", value: "0405", label: "SANTA APOLONIA" },
    { parent: "04", value: "0406", label: "TECPAN GUATEMALA" },
    { parent: "04", value: "0407", label: "PATZUN" },
    { parent: "04", value: "0408", label: "POCHUTA" },
    { parent: "04", value: "0409", label: "PATZICIA" },
    { parent: "04", value: "0410", label: "SANTA CRUZ BALANYA" },
    { parent: "04", value: "0411", label: "ACATENANGO" },
    { parent: "04", value: "0412", label: "SAN PEDRO YEPOCAPA" },
    { parent: "04", value: "0413", label: "SAN ANDRES ITZAPA" },
    { parent: "04", value: "0414", label: "PARRAMOS" },
    { parent: "04", value: "0415", label: "ZARAGOZA" },
    { parent: "04", value: "0416", label: "SAN MIGUEL EL TEJAR" },
    { parent: "05", value: "0501", label: "ESCUINTLA" },
    { parent: "05", value: "0502", label: "SANTA LUCIA COTZUMALGUAPA" },
    { parent: "05", value: "0503", label: "LA DEMOCRACIA" },
    { parent: "05", value: "0504", label: "SIQUINALA" },
    { parent: "05", value: "0505", label: "MASAGUA" },
    { parent: "05", value: "0506", label: "TIQUISATE" },
    { parent: "05", value: "0507", label: "LA GOMERA" },
    { parent: "05", value: "0508", label: "GUANAGAZAPA" },
    { parent: "05", value: "0509", label: "PUERTO SAN JOSE" },
    { parent: "05", value: "0510", label: "IZTAPA" },
    { parent: "05", value: "0511", label: "PALIN" },
    { parent: "05", value: "0512", label: "SAN VICENTE PACAYA" },
    { parent: "05", value: "0513", label: "NUEVA CONCEPCION" },
    { parent: "05", value: "0515", label: "PUERTO DE IZTAPA" },
    { parent: "06", value: "0601", label: "CUILAPA" },
    { parent: "06", value: "0602", label: "BARBERENA" },
    { parent: "06", value: "0603", label: "SANTA ROSA DE LIMA" },
    { parent: "06", value: "0604", label: "CASILLAS" },
    { parent: "06", value: "0605", label: "SAN RAFAEL LAS FLORES" },
    { parent: "06", value: "0606", label: "EL ORATORIO" },
    { parent: "06", value: "0607", label: "SAN JUAN TECUACO" },
    { parent: "06", value: "0608", label: "CHIQUIMULILLA" },
    { parent: "06", value: "0609", label: "TAXISCO" },
    { parent: "06", value: "0610", label: "SANTA MARIA IXHUATAN" },
    { parent: "06", value: "0611", label: "GUAZACAPAN" },
    { parent: "06", value: "0612", label: "SANTA CRUZ NARANJO" },
    { parent: "06", value: "0613", label: "PUEBLO NUEVO VIÑAS" },
    { parent: "06", value: "0614", label: "NUEVA SANTA ROSA" },
    { parent: "07", value: "0701", label: "SOLOLA" },
    { parent: "07", value: "0702", label: "SAN JOSE CHACAYA" },
    { parent: "07", value: "0703", label: "SANTA MARIA VISITACION" },
    { parent: "07", value: "0704", label: "SANTA LUCIA UTATLAN" },
    { parent: "07", value: "0705", label: "NAHUALA" },
    { parent: "07", value: "0706", label: "SANTA CATARINA IXTAHUATAN" },
    { parent: "07", value: "0707", label: "SANTA CLARA LAGUNA" },
    { parent: "07", value: "0708", label: "CONCEPCION" },
    { parent: "07", value: "0709", label: "SAN ANDRES SEMETABAJ" },
    { parent: "07", value: "0710", label: "PANAJACHEL" },
    { parent: "07", value: "0711", label: "SANTA CATARINA PALOPO" },
    { parent: "07", value: "0712", label: "SAN ANTONIO PALOPO" },
    { parent: "07", value: "0713", label: "SAN LUCAS TOLIMAN" },
    { parent: "07", value: "0714", label: "SANTA CRUZ LAGUNA" },
    { parent: "07", value: "0715", label: "SAN PABLO LAGUNA" },
    { parent: "07", value: "0716", label: "SAN MARCOS LAGUNA" },
    { parent: "07", value: "0717", label: "SAN JUAN LAGUNA" },
    { parent: "07", value: "0718", label: "SAN PEDRO LAGUNA" },
    { parent: "07", value: "0719", label: "SANTIAGO ATITLAN" },
    { parent: "08", value: "0801", label: "TOTONICAPAN" },
    { parent: "08", value: "0802", label: "SAN CRISTOBAL TOTONICAPAN" },
    { parent: "08", value: "0803", label: "SAN FRANCISCO EL ALTO" },
    { parent: "08", value: "0804", label: "SAN ANDRES XECUL" },
    { parent: "08", value: "0805", label: "MOMOSTENANGO" },
    { parent: "08", value: "0806", label: "SANTA MARIA CHIQUIMULA" },
    { parent: "08", value: "0807", label: "SANTA LUCIA LA REFORMA" },
    { parent: "08", value: "0808", label: "SAN BARTOLO" },
    { parent: "09", value: "0901", label: "QUETZALTENANGO" },
    { parent: "09", value: "0902", label: "SALCAJA" },
    { parent: "09", value: "0903", label: "OLINTEPEQUE" },
    { parent: "09", value: "0904", label: "SAN CARLOS SIJA" },
    { parent: "09", value: "0905", label: "SIBILIA" },
    { parent: "09", value: "0906", label: "CABRICAN" },
    { parent: "09", value: "0907", label: "CAJOLA" },
    { parent: "09", value: "0908", label: "SAN MIGUEL SIGÜILÁ" },
    { parent: "09", value: "0909", label: "SAN JUAN OSTUNCALCO" },
    { parent: "09", value: "0910", label: "SAN MATEO" },
    { parent: "09", value: "0911", label: "CONCEPCION CHIQUIRICHAPA" },
    { parent: "09", value: "0912", label: "SAN MARTIN SACATEPEQUEZ" },
    { parent: "09", value: "0913", label: "ALMOLONGA" },
    { parent: "09", value: "0914", label: "CANTEL" },
    { parent: "09", value: "0915", label: "HUITAN" },
    { parent: "09", value: "0916", label: "ZUNIL" },
    { parent: "09", value: "0917", label: "COLOMBA" },
    { parent: "09", value: "0918", label: "SAN FRANCISCO LA UNION" },
    { parent: "09", value: "0919", label: "EL PALMAR" },
    { parent: "09", value: "0920", label: "COATEPEQUE" },
    { parent: "09", value: "0921", label: "GENOVA" },
    { parent: "09", value: "0922", label: "FLORES COSTA CUCA" },
    { parent: "09", value: "0923", label: "LA ESPERANZA" },
    { parent: "09", value: "0924", label: "PALESTINA DE LOS ALTOS" },
    { parent: "10", value: "1001", label: "MAZATENANGO" },
    { parent: "10", value: "1002", label: "CUYOTENANGO" },
    { parent: "10", value: "1003", label: "SAN FRANCISCO ZAPOTITLAN" },
    { parent: "10", value: "1004", label: "SAN BERNARDINO" },
    { parent: "10", value: "1005", label: "SAN JOSE EL IDOLO" },
    { parent: "10", value: "1006", label: "SANTO DOMINGO SUCHITEPEQUEZ" },
    { parent: "10", value: "1007", label: "SAN LORENZO" },
    { parent: "10", value: "1008", label: "SAMAYAC" },
    { parent: "10", value: "1009", label: "SAN PABLO JOCOPILAS" },
    { parent: "10", value: "1010", label: "SAN ANTONIO SUCHITEPEQUEZ" },
    { parent: "10", value: "1011", label: "SAN MIGUEL PANAN" },
    { parent: "10", value: "1012", label: "SAN GABRIEL" },
    { parent: "10", value: "1013", label: "CHICACAO" },
    { parent: "10", value: "1014", label: "PATULUL" },
    { parent: "10", value: "1015", label: "SANTA BARBARA" },
    { parent: "10", value: "1016", label: "SAN JUAN BAUTISTA" },
    { parent: "10", value: "1017", label: "SANTO TOMAS LA UNION" },
    { parent: "10", value: "1018", label: "ZUNILITO" },
    { parent: "10", value: "1019", label: "PUEBLO NUEVO" },
    { parent: "10", value: "1020", label: "RIO BRAVO" },
    { parent: "11", value: "1101", label: "RETALHULEU" },
    { parent: "11", value: "1102", label: "SAN SEBASTIAN" },
    { parent: "11", value: "1103", label: "SANTA CRUZ MULUA" },
    { parent: "11", value: "1104", label: "SAN MARTIN ZAPOTITLAN" },
    { parent: "11", value: "1105", label: "SAN FELIPE" },
    { parent: "11", value: "1106", label: "SAN ANDRES VILLA SECA" },
    { parent: "11", value: "1107", label: "CHAMPERICO" },
    { parent: "11", value: "1108", label: "NUEVO SAN CARLOS" },
    { parent: "11", value: "1109", label: "EL ASINTAL" },
    { parent: "11", value: "1110", label: "SAN JOAQUIN MULUA" },
    { parent: "11", value: "1111", label: "SAN JUAN MULUA" },
    { parent: "12", value: "1201", label: "SAN MARCOS" },
    { parent: "12", value: "1202", label: "SAN PEDRO SACATEPEQUEZ" },
    { parent: "12", value: "1203", label: "SAN ANTONIO SACATEPEQUEZ" },
    { parent: "12", value: "1204", label: "COMITANCILLO" },
    { parent: "12", value: "1205", label: "SAN MIGUEL IXTAHUACAN" },
    { parent: "12", value: "1206", label: "CONCEPCION TUTUAPA" },
    { parent: "12", value: "1207", label: "TACANA" },
    { parent: "12", value: "1208", label: "SIBINAL" },
    { parent: "12", value: "1209", label: "TAJUMULCO" },
    { parent: "12", value: "1210", label: "TEJUTLA" },
    { parent: "12", value: "1211", label: "SAN RAFAEL PIE DE LA CUESTA" },
    { parent: "12", value: "1212", label: "NUEVO PROGRESO" },
    { parent: "12", value: "1213", label: "EL TUMBADOR" },
    { parent: "12", value: "1214", label: "SAN JOSE EL RODEO" },
    { parent: "12", value: "1215", label: "MALACATAN" },
    { parent: "12", value: "1216", label: "CATARINA" },
    { parent: "12", value: "1217", label: "TECUN UMAN / AYUTLA" },
    { parent: "12", value: "1218", label: "OCOS" },
    { parent: "12", value: "1220", label: "EL QUETZAL" },
    { parent: "12", value: "1221", label: "LA REFORMA" },
    { parent: "12", value: "1222", label: "PAJAPITA" },
    { parent: "12", value: "1223", label: "IXCHIGUA" },
    { parent: "12", value: "1224", label: "SAN JOSE OJETENAM" },
    { parent: "12", value: "1225", label: "SAN CRISTOBAL CUCHO" },
    { parent: "12", value: "1226", label: "SIPACAPA" },
    { parent: "12", value: "1227", label: "ESQUIPULAS PALO GORDO" },
    { parent: "12", value: "1228", label: "RIO BLANCO" },
    { parent: "12", value: "1229", label: "SAN LORENZO" },
    { parent: "12", value: "1219", label: "SAN PABLO" },
    { parent: "13", value: "1301", label: "HUEHUETENANGO" },
    { parent: "13", value: "1302", label: "CHIANTLA" },
    { parent: "13", value: "1303", label: "MALACATANCITO" },
    { parent: "13", value: "1304", label: "CUILCO" },
    { parent: "13", value: "1305", label: "NENTON" },
    { parent: "13", value: "1306", label: "SAN PEDRO NECTA" },
    { parent: "13", value: "1307", label: "JACALTENANGO" },
    { parent: "13", value: "1308", label: "SAN PEDRO SOLOMA" },
    { parent: "13", value: "1309", label: "SAN ILDEFONSO IXTAHUACAN" },
    { parent: "13", value: "1310", label: "SANTA BARBARA" },
    { parent: "13", value: "1311", label: "LA LIBERTAD" },
    { parent: "13", value: "1312", label: "LA DEMOCRACIA" },
    { parent: "13", value: "1313", label: "SAN MIGUEL ACATAN" },
    { parent: "13", value: "1314", label: "SAN RAFAEL INDEPENDENCIA" },
    { parent: "13", value: "1315", label: "TODOS SANTOS CUCHUMATANES" },
    { parent: "13", value: "1316", label: "SAN JUAN ATITAN" },
    { parent: "13", value: "1317", label: "SANTA EULALIA" },
    { parent: "13", value: "1318", label: "SAN MATEO IXTATAN" },
    { parent: "13", value: "1319", label: "COLOTENANGO" },
    { parent: "13", value: "1320", label: "SAN SEBASTIAN HUEHUETENANGO" },
    { parent: "13", value: "1321", label: "TECTITAN" },
    { parent: "13", value: "1322", label: "CONCEPCION HUISTA" },
    { parent: "13", value: "1323", label: "SAN JUAN IXCOY" },
    { parent: "13", value: "1324", label: "SAN ANTONIO HUISTA" },
    { parent: "13", value: "1325", label: "SAN SEBASTIAN COATAN" },
    { parent: "13", value: "1326", label: "SANTA CRUZ BARILLAS" },
    { parent: "13", value: "1327", label: "AGUACATAN" },
    { parent: "13", value: "1328", label: "SAN RAFAEL PETZAL" },
    { parent: "13", value: "1329", label: "SAN GASPAR IXCHIL" },
    { parent: "13", value: "1330", label: "SANTIAGO CHIMALTENANGO" },
    { parent: "13", value: "1331", label: "SANTA ANA HUISTA" },
    { parent: "14", value: "1401", label: "SANTA CRUZ DEL QUICHE" },
    { parent: "14", value: "1402", label: "CHICHE" },
    { parent: "14", value: "1403", label: "CHINIQUE" },
    { parent: "14", value: "1404", label: "ZACUALPA" },
    { parent: "14", value: "1405", label: "CHAJUL" },
    { parent: "14", value: "1406", label: "CHICHICASTENANGO" },
    { parent: "14", value: "1407", label: "PATZITE" },
    { parent: "14", value: "1408", label: "SAN ANTONIO ILOTENANGO" },
    { parent: "14", value: "1409", label: "SAN PEDRO JOCOPILAS" },
    { parent: "14", value: "1410", label: "CUNEN" },
    { parent: "14", value: "1411", label: "SAN JUAN COTZAL" },
    { parent: "14", value: "1412", label: "JOYABAJ" },
    { parent: "14", value: "1413", label: "NEBAJ" },
    { parent: "14", value: "1414", label: "SAN ANDRES SAJCABAJA" },
    { parent: "14", value: "1415", label: "USPANTAN" },
    { parent: "14", value: "1416", label: "SACAPULAS" },
    { parent: "14", value: "1417", label: "SAN BARTOLOME JOCOTENANGO" },
    { parent: "14", value: "1418", label: "CANILLA" },
    { parent: "14", value: "1419", label: "CHICAMAN" },
    { parent: "14", value: "1420", label: "IXCAN PLAYA GRANDE" },
    { parent: "14", value: "1421", label: "PACHALUM" },
    { parent: "15", value: "1501", label: "SALAMA" },
    { parent: "15", value: "1502", label: "SAN MIGUEL CHICAJ" },
    { parent: "15", value: "1503", label: "RABINAL" },
    { parent: "15", value: "1504", label: "CUBULCO" },
    { parent: "15", value: "1505", label: "GRANADOS" },
    { parent: "15", value: "1506", label: "EL CHOL" },
    { parent: "15", value: "1507", label: "SAN JERONIMO" },
    { parent: "15", value: "1508", label: "PURULHA" },
    { parent: "16", value: "1601", label: "COBAN" },
    { parent: "16", value: "1602", label: "SANTA CRUZ VERAPAZ" },
    { parent: "16", value: "1603", label: "SAN CRISTOBAL VERAPAZ" },
    { parent: "16", value: "1604", label: "TACTIC" },
    { parent: "16", value: "1605", label: "TAMAHU" },
    { parent: "16", value: "1606", label: "SAN MIGUEL TUCURU" },
    { parent: "16", value: "1607", label: "PANZOS" },
    { parent: "16", value: "1608", label: "SENAHU" },
    { parent: "16", value: "1609", label: "SAN PEDRO CARCHA" },
    { parent: "16", value: "1610", label: "SAN JUAN CHAMELCO" },
    { parent: "16", value: "1611", label: "LANQUIN" },
    { parent: "16", value: "1612", label: "SANTA MARIA CAHABON" },
    { parent: "16", value: "1613", label: "CHISEC" },
    { parent: "16", value: "1614", label: "CHAHAL" },
    { parent: "16", value: "1615", label: "FRAY BARTOLOME DE LAS CASAS" },
    { parent: "17", value: "1701", label: "CIUDAD FLORES" },
    { parent: "17", value: "1702", label: "SAN JOSE" },
    { parent: "17", value: "1703", label: "SAN BENITO" },
    { parent: "17", value: "1704", label: "SAN ANDRES" },
    { parent: "17", value: "1705", label: "LA LIBERTAD" },
    { parent: "17", value: "1706", label: "SAN FRANCISCO" },
    { parent: "17", value: "1707", label: "SANTA ANA" },
    { parent: "17", value: "1708", label: "DOLORES" },
    { parent: "17", value: "1709", label: "SAN LUIS" },
    { parent: "17", value: "1710", label: "SAYAXCHE" },
    { parent: "17", value: "1711", label: "MELCHOR DE MENCOS" },
    { parent: "17", value: "1712", label: "POPTUN" },
    { parent: "17", value: "1713", label: "SANTA ELENA" },
    { parent: "17", value: "1714", label: "LAS CRUCES" },
    { parent: "18", value: "1801", label: "PUERTO BARRIOS" },
    { parent: "18", value: "1802", label: "LIVINGSTON" },
    { parent: "18", value: "1803", label: "EL ESTOR" },
    { parent: "18", value: "1804", label: "MORALES" },
    { parent: "18", value: "1805", label: "LOS AMATES" },
    { parent: "18", value: "1806", label: "RIO DULCE" },
    { parent: "19", value: "1901", label: "ZACAPA" },
    { parent: "19", value: "1902", label: "ESTANZUELA" },
    { parent: "19", value: "1903", label: "RIO HONDO" },
    { parent: "19", value: "1904", label: "GUALAN" },
    { parent: "19", value: "1905", label: "TECULUTAN" },
    { parent: "19", value: "1906", label: "USUMATLAN" },
    { parent: "19", value: "1907", label: "CABAÑAS" },
    { parent: "19", value: "1908", label: "SAN DIEGO" },
    { parent: "19", value: "1909", label: "LA UNION" },
    { parent: "19", value: "1910", label: "HUITE" },
    { parent: "20", value: "2001", label: "CHIQUIMULA" },
    { parent: "20", value: "2002", label: "SAN JOSE LA ARADA" },
    { parent: "20", value: "2003", label: "SAN JUAN ERMITA" },
    { parent: "20", value: "2004", label: "JOCOTAN" },
    { parent: "20", value: "2005", label: "CAMOTAN" },
    { parent: "20", value: "2006", label: "OLOPA" },
    { parent: "20", value: "2007", label: "ESQUIPULAS" },
    { parent: "20", value: "2008", label: "CONCEPCION LAS MINAS" },
    { parent: "20", value: "2009", label: "QUETZALTEPEQUE" },
    { parent: "20", value: "2010", label: "SAN JACINTO" },
    { parent: "20", value: "2011", label: "IPALA" },
    { parent: "21", value: "2101", label: "JALAPA" },
    { parent: "21", value: "2102", label: "SAN PEDRO PINULA" },
    { parent: "21", value: "2103", label: "SAN LUIS JILOTEPEQUE" },
    { parent: "21", value: "2104", label: "SAN MANUEL CHAPARRON" },
    { parent: "21", value: "2105", label: "SAN CARLOS ALZATATE" },
    { parent: "21", value: "2106", label: "MONJAS" },
    { parent: "21", value: "2107", label: "MATAQUESCUINTLA" },
    { parent: "22", value: "2201", label: "JUTIAPA" },
    { parent: "22", value: "2202", label: "EL PROGRESO" },
    { parent: "22", value: "2203", label: "SANTA CATARINA MITA" },
    { parent: "22", value: "2204", label: "AGUA BLANCA" },
    { parent: "22", value: "2205", label: "ASUNCION MITA" },
    { parent: "22", value: "2206", label: "YUPILTEPEQUE" },
    { parent: "22", value: "2207", label: "ATESCATEMPA" },
    { parent: "22", value: "2208", label: "JEREZ" },
    { parent: "22", value: "2209", label: "EL ADELANTO" },
    { parent: "22", value: "2210", label: "ZAPOTITLAN" },
    { parent: "22", value: "2211", label: "COMAPA" },
    { parent: "22", value: "2212", label: "JALPATAGUA" },
    { parent: "22", value: "2213", label: "CONGUACO" },
    { parent: "22", value: "2214", label: "MOYUTA" },
    { parent: "22", value: "2215", label: "PASACO" },
    { parent: "22", value: "2216", label: "SAN JOSE ACATEMPA" },
    { parent: "22", value: "2217", label: "QUEZADA" },
    { parent: "00", value: "0000", label: "NO DEFINIDA" },
    { parent: "12", value: "1230", label: "LA BLANCA" },
    { parent: "17", value: "1715", label: "EL CHAL" },
    { parent: "13", value: "1332", label: "UNION CANTINIL" },
    { parent: "05", value: "0514", label: "SIPACATE" },
    { parent: "10", value: "1021", label: "SAN JOSE LA MAQUINA" },
    { parent: "16", value: "1617", label: "RAXRUHA" },
    { parent: "13", value: "1333", label: "PETATAN" },
    { parent: "16", value: "1616", label: "SANTA CATARINA LA TINTA" },
    { parent: "19", value: "1911", label: "SAN JORGE" }*/
];