export default {
  //MENU
  'psp.titulo': 'Prospección',
  'psp.campaniaSinNombre': 'Sin Nombre',
  'psp.lblCampania': 'Campaña',
  'psp.lblMonto': 'Monto',
  'psp.lblPeriodos': 'Periodos',
  'psp.lblGuardar': 'Guardar',
  'psp.observacion': 'Observación',
  'psp.lblNumeroCelular': 'Número Celular',
  'psp.lblCelular': 'Celular',
  'psp.lblConvencional': 'Convencional',
  'psp.lblFax': 'Fax',

  //Agendamiento Modal
  'psp.tituloReagendar': 'Reagendar',
  'psp.fechaAgendamiento': 'Fecha Agendamiento',
  'psp.agendadaExitosa': 'Prospección Agendada',

  //Rechazar Modal
  'psp.tituloRechazar': 'Rechazar',
  'psp.motivoRechaza': 'Motivo',
  'psp.rechazadaExitosa': 'Prospección Rechazada',
  'psp.lblAsesorDos': 'Asesor: ',
  'psp.lblClienteDos': 'Cliente: ',

  //SearchClient
  'psp.lblTipoIdentificacion': 'Tipo Identificación',
  'psp.lblIdentificacion': 'Identificación',

  'psp.btnBuscarCliente': 'Buscar Cliente',
  'psp.btnConsultaBuro': 'Consultar Buró',
  'psp.lblFechaNacimiento': 'Fecha Nacimiento',
  'psp.lblSegundoApellido': 'Segundo Apellido',
  'psp.lblPrimerApellido': 'Primer Apellido',
  'psp.lblSegundoNombre': 'Segundo Nombre',
  'psp.lblPrimerNombre': 'Primer Nombre',

  //INFORMATION
  'psp.lblCodigoAsesor': 'Código Asesor',
  'psp.btnValidarArbol': 'Validar',
  'psp.lblFuenteIngresos': 'Fuente de Ingresos',
  'psp.lblOrigenIngresos': 'Origen Ingresos',
  'psp.lblSubOrigenIngresos': 'Subtipo Origen Ingreso',
  'psp.lblIngresos': 'Ingresos',
  'psp.lblTipoGarantia': 'Tipo de Garantía',
  'psp.lblProfesion': 'Profesión',
  'psp.lblSector': 'Sector',

  //SALARIADO
  'psp.lblAniosAntiguedad': 'Años Antigüedad',
  'psp.lblMesesAntiguedad': 'Meses Antigüedad',

  ///VENTAS
  'psp.lblAniosExperiencia': 'Años Experiencia',
  'psp.lblMesesExperiencia': 'Meses Experiencia',

  //RENTAS
  'psp.lblAniosRecibirlas': 'Años de Recibirlas',
  'psp.lblMesesRecibirlas': 'Meses de Recibirlas',
  'psp.lblNacionalidad': 'Nacionalidad',
  'psp.lblNivelEducacion': 'Nivel Educación',
  'psp.lblEstadoCivil': 'Estado Civil',
  'psp.lblIdentificacionConyu': 'No. Id. Cónyuge',
  'psp.lblGenero': 'Género',
  'psp.lblTipoVidienda': 'Tipo de Vivienda',
  'psp.lblCargaFamiliar': 'Cargas Familiares',
  'psp.lblDestinoCredito': 'Destino Crédito',
  'psp.lblDepartamentoNegocio': 'Departamento Negocio',
  'psp.lblMunicipioNegocio': 'Municipio Negocio',
  'psp.lblMunicipio': 'Municipio',
  'psp.lblSectorNegocio': 'Sector Negocio',
  'psp.lblGiroNegocio': 'Giro de Negocio',
  'psp.lblDomicilio': 'Domicilio',
  'psp.lblLaboral': 'Laboral',
  'psp.lblRegion': 'Región',
  'psp.titleAlert': 'Prospección',

  //Oferta
  'psp.lblOfertaMaxima': 'Oferta Máxima',
  'psp.lblOferta': 'Oferta',
  'psp.lblOfertaEspecial': 'Oferta Especial',
  'psp.tituloCliBloqueos': ' Cliente Presenta Bloqueos',

  //Requested Offer
  'psp.lblMontoLiquido': 'Monto Líquido',
  'psp.tituloOfertaSugerida': 'Oferta Sugerida',
  'psp.tituloOfertaSolicitada': 'Oferta Solicitada',
  'psp.lblFchVencimiento': 'Fecha Vencimiento',
  'psp.lblTabla': 'Tabla',
  'psp.lblCuota': 'Cuota',
  'psp.lblDestino': 'Destino',
  'psp.lblDesembolso': 'Desembolso',
  'psp.lblCtaDesembolso': 'Cta. Desembolso',
  'psp.btnCalcular': 'Calcular Cuota',
  'psp.tituloRetanqueo': 'Operaciones Vigentes',
  'psp.lblProducto': 'Producto',
  'psp.lblSaldo': 'Saldo',
  'psp.btnSeguros': 'Seguros',
  'psp.lblTelefono': 'Teléfono',
  'psp.lblTipoTelefono': 'Tipo Teléfono',
  'psp.lblNumero': 'Número',
  'psp.lblCorreo': 'Mail',
  'psp.lblDireccion': 'Dirección',
  'psp.lblCalleP': 'Principal',
  'psp.lblCalleS': 'Secundaria',
  'psp.AlertBloq': 'Cliente presenta bloqueos, por lo tanto no es posible continuar.',
  'psp.lblSeguros': 'Seguros',
  'psp.lblSegurosObligatorios': 'Seguros Obligatorios',
  'psp.lblSegurosVoluntarios': 'Seguros Voluntarios',
  'psp.textAceptaOferta': 'Oferta Aprobada',
  'psp.tablaAmortizacion': 'Tabla Amortización',
  'psp.ClienteGestionado': 'Este cliente ya fue gestionado',
  'psp.portfolio.noData': 'No tiene tareas asignadas',
  'psp.portfolio.item.numeroSolicitud': 'Solicitud',
  'psp.portfolio.item.identificacion': 'Identificación',
  'psp.portfolio.item.nombres': 'Nombres',
  'psp.portfolio.item.producto': 'Producto',
  'psp.portfolio.item.codigoProducto': 'Código',
  'psp.portfolio.item.codigoSubProducto': 'Código sub-producto',
  'psp.portfolio.item.tipoCliente': 'Tipo cliente',
  'psp.portfolio.item.tipoControl': 'Tipo control',
  'psp.portfolio.item.esReingreso': 'Reingreso',

  //Gestion
  'psp.lblDepartamento': 'Departamento',
  'psp.lblCanton': 'Cantón',
  'psp.lblAldea': 'Aldea',
  'psp.lblUbReferencia': 'Ubicación de Referencia',
  'psp.TituloNuevDireccion': 'Nueva Dirección',
  'psp.transaction.ok': 'Transacción Exitosa',
  'psp.enablingDocuments.cliente': 'Cliente',
  'psp.enablingDocuments.garante': 'Garante',
  'psp.enablingDocuments.promover': 'Promover',
  'psp.enablingDocuments.usuario.noasignado': 'Ya no tiene asignada la tarea',
  'psp.noData': 'No Hay Información',
  'psp.lblNit': 'Nit',

  //Campañas
  'psp.fechaInicioCamp': 'Fecha Inicio Campaña: ',
  'psp.fechaFinCamp': 'Fecha Fin Campaña: ',
  'psp.camp': 'Campaña: ',
  'psp.numNoGestionadas': 'No Gestionadas: ',
  'psp.numGestionadas': 'Gestionadas: ',
  'psp.Comentario': 'Comentario',
  'psp.msgTercero': 'Mensaje Tercero',
  'psp.campoObligatorio': 'Obligatorio',
  'psp.motivoNoContact': 'Motivo',
  'psp.lblDocumento': 'Documento',
  'psp.noGestionNingunCliente': 'No has gestionado ningún cliente.',
  'psp.noSeHaVendido': 'No se ha generado ninguna Venta',
  'psp.InformacionAdicional': 'Información Adicional',
  'psp.ResultadoGestionGuardado': 'Resultado de la gestión guardado exitosamente.',
  'psp.TituloInfoAdicional': 'Información Adicional',
  'psp.ConfirmacionVenta': '¿Está seguro/a de Generar la Solicitud con las condiciones de crédito Solicitadas?',
  'psp.ConfirTrxTitle': 'Confirmar Transacción',
  'psp.NoRegistros': 'No. de Registros: ',
  'psp.modalGestionesTitle': "Gestiones",

  'psp.tituloAppointment': "Detalle Agendamiento",
  'psp.tituloEditarAppointment': "Editar Agendamiento",
  'psp.titulo': "Título",
  'psp.descripcion': "Descripción",
  'psp.horaInicio': "Hora Inicio",
  'psp.horaFin': "Hora Fin",
  'psp.lblEditar': 'Editar',
  'psp.lblZona': 'Zona',
  'psp.lblAvenida': 'Avenida',
  'psp.lblDireccionLaboral': 'Dirección Laboral',
  'psp.lblDireccionDomicilio': 'Dirección Domicilio',
  'psp.lblMotivDevoVFS': 'Motivo Devolución VFS',
  'psp.lblObsDevolucion': 'Observación Devolución',
  "psp.UsrDevolucon": "Usuario Devolución",
  'psp.lblObsPorDevolucion': "Observaciones por Devolución",
  'psp.lblDispUbicacion': "Dispositivo Ubicación",
  'psp.lblConsultarConFiltro': "Consultar con filtro",
  'psp.lblAgencia': 'Agencia',
  'psp.lblNombreEmpresa': 'Nombre Empresa',
  'psp.tltConsultarEmpresa': 'Consultar Empresa',
  'psp.lblConEmpresa': 'Consultar Empresa',
  'psp.lblBuscar': 'Buscar',
  'psp.lblNoDataEmpresas': 'No hay empresas',

  'psp.lblTipoRelacion': 'Tipo Relación',
  'psp.lblRelacionParentesco': 'Relación Parentesco',
  'psp.lblHorarioUbicacion': 'Horario Ubicación',
  'psp.ObsUbicacion': 'Observación Ubicación',
  'psp.tltNuevReferOblig': "Nueva Referencia Obligatoria",
  'psp.tltNuevReferOpc': "Nueva Referencia Opcional",
  "psp.lblReferencia": "Referencia",
  "psp.lblParentesco": "Parentesco",
  'psp.lblEstado': "Estado",
  'psp.lblMotivo': "Motivo",
  'psp.ComentarioDevol': 'Comentario Devolución',

  'psp.lblNoContador': 'No. Contador',
  'psp.lblValorVivienda': 'Valor Vivienda',
  'psp.lblAniosVivienda': 'Años Vivienda',
  'psp.lblMesesVivienda': 'Meses Vivienda',
  'psp.lblDireccionNegocio': 'Dirección Negocio',
  'psp.lblValorDispUbica': 'Valor',

  'psp.consultaUnificada.tipo': 'Tipo',
  'psp.consultaUnificada.valor': 'Valor',
  'psp.consultaUnificada.buscar': 'Buscar',
  'psp.consultaUnificada.buscando': "Buscando",
  'psp.consultaUnificada.resumenCredito': 'Resumen Crédito',
  'psp.consultaUnificada.informacionCliente': 'Información Solicitud',
  'psp.consultaUnificada.nombres': 'Nombres',
  'psp.consultaUnificada.numeroSolicitud': 'Número solicitud',
  'psp.consultaUnificada.perfil': 'Perfil',
  'psp.consultaUnificada.producto': 'Producto',
  'psp.consultaUnificada.fechaSolicitud': 'Fecha solicitud',
  'psp.consultaUnificada.estadoSolicitud': 'Estado solicitud',
  'psp.consultaUnificada.estadoDocumentacion': 'Estado documentación',
  'psp.consultaUnificada.nombreUsuario': 'Usuario creación',
  'psp.consultaUnificada.comentario': 'Observación',
  'psp.consultaUnificada.actividadSolicitud': 'Actividad Solicitud',
  'psp.consultaUnificada.analisisTelefonico': 'Análisis Telefónico',
  'psp.consultaUnificada.analisisDomiciliar': 'Análisis Domiciliar',
  'psp.consultaUnificada.analisisLaboral': 'Análisis Laboral',
  'psp.consultaUnificada.estado': 'Estado',
  'psp.consultaUnificada.verificador': 'Verificador',
  'psp.consultaUnificada.fechaVerificacion': 'Fecha Verificación',
  'psp.consultaUnificada.comentario': 'Comentario',
  'psp.consultaUnificada.departamento': 'Departamento',
  'psp.consultaUnificada.municipio': 'Municipio',
  'psp.consultaUnificada.zona': 'Zona',
  'psp.consultaUnificada.localidad': 'Localidad',
  'psp.consultaUnificada.callePrincipal': 'Calle Principal',
  'psp.consultaUnificada.calleTransversal': 'Avenida',
  'psp.consultaUnificada.numeroVivienda': 'Número',
  'psp.consultaUnificada.referencia': 'Referencia',
  'psp.consultaUnificada.cargando': 'Cargando',
  'psp.consultaUnificada.titulo': 'Consulta Unificada',
  'psp.consultaUnificada.tituloOfertas': 'Ofertas',





  //MOVER A COMMON
  'psp.TituloDetalleNotificacion': "Detalle Notificación",
  'psp.tltBtnBorrarNotif': "Borrar notificación de mi buzón"
};




