import { Model } from '@nozbe/watermelondb';
import {
  field,
  date,
  children,
  lazy,
  action,
  relation,
} from '@nozbe/watermelondb/decorators';

export default class Prospect extends Model {
  static table = 'prospects';

  /* FIELDS */
  @field("numeroSolicitud")
  numeroSolicitud
  @field("idAsesor")
  idAsesor
  @field("idDetalleAsignacionRecurso")
  idDetalleAsignacionRecurso
  @field("idCampania")
  idCampania
  @field("idCliente")
  idCliente
  @field("idClienteCampania")
  idClienteCampania
  @field("nombreCampania")
  nombreCampania
  @field("fechaInicioCampania")
  fechaInicioCampania
  @field("fechaFinCampania")
  fechaFinCampania
  @field("tipoIdentificacion")
  tipoIdentificacion
  @field("identificacion")
  identificacion
  @field("nombreCliente")
  nombreCliente
  @field("perfilConsumo")
  perfilConsumo
  @field("tipoClienteComercial")
  tipoClienteComercial
  @field("grupoAgenciaConsumo")
  grupoAgenciaConsumo
  @field("primerNombre")
  primerNombre
  @field("segundoNombre")
  segundoNombre
  @field("primerApellido")
  primerApellido
  @field("segundoApellido")
  segundoApellido
  @field("numeroGestiones")
  numeroGestiones
  @field("codigoSubProducto")
  codigoSubProducto
  @field("codigoProducto")
  codigoProducto
  @field("tasa")
  tasa
  @field("monto")
  monto
  @field("plazo")
  plazo
  @field("seGestiono")
  seGestiono
  @field("tipoControl")
  tipoControl
  @field("tipoGestion")
  tipoGestion
  @field("dispositivo")
  dispositivo
  @field("direccion")
  direccion
  @field("correo")
  correo
  @field("fechaGestiono")
  fechaGestiono
  @field("noContactadoCom")
  noContactadoCom
  @field("noContactMotivo")
  noContactMotivo
  @field("noCumplePolCom")
  noCumplePolCom
  @field("msgTercero")
  msgTercero
  @field("cuota")
  cuota
  @field("tiempoRespuesta")
  tiempoRespuesta
  @field("motivosNoContactados")
  motivosNoContactados
  @field("datosRangoProducto")
  datosRangoProducto
  @field("numeroReferenciaSIB")
  numeroReferenciaSIB
  @field("tipoControlModifica")
  tipoControlModifica
  @field("descripcionProducto")
  descripcionProducto
  @field("idArbolRespuesta")
  idArbolRespuesta
}
